version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: ower94/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    container_name: 'web'
    env_file:
      - ./.env
  
  frontend:
    image: ower94/foodgram-front:latest
    volumes:
      - ./frontend/:/app/result_build/
    container_name: 'frontend'

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "81:81"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
    container_name: 'nginx'

volumes:
  static_value:
  media_value:
  postgres_db:
  redoc: