# Generated by Django 3.2 on 2022-12-11 14:00

from django.db import migrations

INGREDIENTS = open('./data/ingredients.json')


def add_ingridient(apps, schema_editor):
    Ingridient = apps.get_model('Ingredient')
    for ingredient in INGREDIENTS:
        new_ingredient = Ingridient(**ingredient)
        new_ingredient.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_ingridient,
        )
    ]
