# Generated by Django 3.2.16 on 2023-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_add_ingridient_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='FF', max_length=7, null=True, verbose_name='Цветовой HEX-код'),
        ),
    ]
